name: List GitHub Admins of a Repository
description: Retrieve a list of GitHub Administrators of a repository
title: "List GitHub Admins of a Repo: [repo-name]"
labels: [ admin-repo ]
body:
  - type: input
    id: repo
    attributes:
      label: GitHub Repository
      description: GitHub repository to retrieve admins
    validations:
      required: true
