name: List GitHub Admins of a Repository
description: Retrieve a list of GitHub Administrators for the repository below
title: "List GitHub Admins of a Repository"
labels: [ admin-repo ]
body:
  - type: input
    id: repo
    attributes:
      label: GitHub Repository
      description: GitHub repository to retrieve admins
    validations:
      required: true
